-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 09:44:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema manzi_serge
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `manzi_serge` ;

-- -----------------------------------------------------
-- Schema manzi_serge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manzi_serge` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `manzi_serge` ;

-- -----------------------------------------------------
-- Table `manzi_serge`.`assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manzi_serge`.`assignments` ;

CREATE TABLE IF NOT EXISTS `manzi_serge`.`assignments` (
  `ass_id` INT NOT NULL,
  `giver` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `duration` TEXT NOT NULL,
  `pay/hour` TEXT NOT NULL,
  `result` TEXT NULL DEFAULT NULL,
  `giver contacts` INT NULL DEFAULT NULL,
  `seekr_name` TEXT NOT NULL,
  `seeker_contacts` INT NOT NULL,
  PRIMARY KEY (`ass_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `manzi_serge`.`epayments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manzi_serge`.`epayments` ;

CREATE TABLE IF NOT EXISTS `manzi_serge`.`epayments` (
  `pay_id` INT NOT NULL,
  `js_username` TEXT NOT NULL,
  `jg_username` TEXT NOT NULL,
  `cituantion` INT NOT NULL,
  `admin_id` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `manzi_serge`.`job_givers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manzi_serge`.`job_givers` ;

CREATE TABLE IF NOT EXISTS `manzi_serge`.`job_givers` (
  `job_giver_id` INT NOT NULL AUTO_INCREMENT,
  `national_id` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `Password` INT NOT NULL,
  `Names` VARCHAR(40) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `address` VARCHAR(20) NOT NULL,
  `contacts` INT NOT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`job_giver_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 654325
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `manzi_serge`.`job_seekers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manzi_serge`.`job_seekers` ;

CREATE TABLE IF NOT EXISTS `manzi_serge`.`job_seekers` (
  `job_seeker_id` INT NOT NULL,
  `national_id` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `Password` TEXT NOT NULL,
  `Names` VARCHAR(40) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `address` VARCHAR(20) NOT NULL,
  `contacts` INT NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `field_of_interest` VARCHAR(50) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `manzi_serge`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manzi_serge`.`tasks` ;

CREATE TABLE IF NOT EXISTS `manzi_serge`.`tasks` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(20) NOT NULL,
  `type_of_task` VARCHAR(20) NOT NULL,
  `duration` VARCHAR(20) NULL DEFAULT NULL,
  `starting_dates` TEXT NOT NULL,
  `g_username` TEXT NOT NULL,
  `job_seeker_id` INT NULL DEFAULT NULL,
  `payment_per_hour` INT NULL DEFAULT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `manzi_serge`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manzi_serge`.`users` ;

CREATE TABLE IF NOT EXISTS `manzi_serge`.`users` (
  `admin_id` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(10) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `manzi_serge` ;

-- -----------------------------------------------------
-- procedure Into_j_givers
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`Into_j_givers`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Into_j_givers`(`job_giver_id` INT(10), `national_id` INT(10), `Fname` VARCHAR(20), `L_name` VARCHAR(20), `DOB` DATE, `gender` VARCHAR(6), `address` VARCHAR(20), `contacts` VARCHAR(15), `email` VARCHAR(25))
BEGIN insert into job_givers VALUEs(job_giver_id, national_id,fname,lname,dob,gender,address,contacts,Email); END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deletej_giver
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`deletej_giver`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deletej_giver`(IN `job_giver_ID` INT(10))
BEGIN DELETE FROM job_givers WHERE job_giver_ID=jobgiver_id; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deletej_seeker
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`deletej_seeker`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deletej_seeker`(IN `job_seeker_id` INT(10))
BEGIN DELETE FROM job_seekers WHERE job_seeker_id=job_seeker_id; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure into_epayment
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`into_epayment`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `into_epayment`(IN `pay_id` INT(10), IN `pay_mode` VARCHAR(20), IN `amount` INT(7), IN `date_of_payment` DATE, IN `job_seeker_id` INT(10), IN `job_giver_id` INT(10), IN `payment_per_hour` INT(5), IN `reason` VARCHAR(20))
BEGIN insert into epayments values(pay_id,pay_mode,amount,date_of_payment,job_seeker_id,job_giver_id,payment_per_hour); END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure job_giver_info
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`job_giver_info`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `job_giver_info`()
BEGIN SELECT * FROM job_giversver; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure job_seeke_info
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`job_seeke_info`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `job_seeke_info`()
BEGIN SELECT* FROM job_seekers; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sq_task
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`sq_task`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sq_task`(`task_ID` INT(10), `task_name` VARCHAR(20), `type_of_task` VARCHAR(20), `duration` VARCHAR(20), `start_date` DATE, `job_giver_id` INT(10), `job_seeker_ID` INT(10), `pay_per_hour` INT(5))
BEGIN SELECT* from tasks where task_ID<(SELECT(task_ID) from tasks); END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updatej_givers
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`updatej_givers`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updatej_givers`(IN `job_giver_id` VARCHAR(10))
BEGIN UPDATE job_seekers SET address='Ruhango-centre' WHERE job_giver_id=job_giver_id; END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updatej_seekers
-- -----------------------------------------------------

USE `manzi_serge`;
DROP procedure IF EXISTS `manzi_serge`.`updatej_seekers`;

DELIMITER $$
USE `manzi_serge`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updatej_seekers`(IN `job_seeker_id` INT(10))
BEGIN UPDATE job_seekers set Fname='muyomba' where job_seeker_id=job_seeker_ID; END$$

DELIMITER ;
USE `manzi_serge`;

DELIMITER $$

USE `manzi_serge`$$
DROP TRIGGER IF EXISTS `manzi_serge`.`delete_trigger` $$
USE `manzi_serge`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `manzi_serge`.`delete_trigger`
AFTER DELETE ON `manzi_serge`.`epayments`
FOR EACH ROW
delete from epayments WHERE epayments.admin_id=users.admin_id$$


USE `manzi_serge`$$
DROP TRIGGER IF EXISTS `manzi_serge`.`after_delete_job_giver` $$
USE `manzi_serge`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `manzi_serge`.`after_delete_job_giver`
AFTER DELETE ON `manzi_serge`.`job_givers`
FOR EACH ROW
BEGIN
DELETE from users where users.job_giver_id=OLD.job_giver_id;
END$$


USE `manzi_serge`$$
DROP TRIGGER IF EXISTS `manzi_serge`.`after_delete_job_seeker` $$
USE `manzi_serge`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `manzi_serge`.`after_delete_job_seeker`
AFTER DELETE ON `manzi_serge`.`job_seekers`
FOR EACH ROW
BEGIN
DELETE from users where users.job_seeker_id_ID=OLD.job_seeker_ID;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
